cargo-features = ["per-package-target"]

[package]
name = "sha3-ex"
version = "0.1.0"
edition = "2021"

[dependencies]
jolt-sdk = { path = "../../jolt-sdk", features = ["std"] }

hex = "0.4.3"
sha3 = { version = "0.10.8", default-features = false }
