[package]
name = "jolt-sdk"
version = "0.1.0"
authors = [
    "Michael Zhu <mzhu@a16z.com>",
    "Sam Ragsdale <sragsdale@a16z.com>",
    "Noah Citron <ncitron@a16z.com>"
]
description = "SDK for Jolt"
license = "MIT"
homepage = "https://github.com/a16z/lasso/README.md"
repository = "https://github.com/a16z/lasso"
edition="2021"

[features]
std = ["dep:tracer", "dep:common", "postcard/use-std"]

[dependencies]
postcard = { version = "1.0.8", default-features = false }
serde = { version = "1.0.*", default-features = false }

jolt-sdk-macros = { path = "./macros" }
tracer = { path = "../tracer", optional = true }
common = { path = "../common", optional = true }
