[package]
name = "jolt-core"
version = "0.1.0"
authors = [
    # author of original Spartan paper and code base 
    "Srinath Setty <srinath@microsoft.com>",
    # authors who contributed to the Arkworks Spartan fork
    "Zhenfei Zhang <zhenfei.zhang@hotmail.com>",
    # authors who contributed to Lasso
    "Michael Zhu <mzhu@a16z.com>",
    "Sam Ragsdale <sragsdale@a16z.com>",
    "Noah Citron <ncitron@a16z.com>",
]
edition = "2021"
description = "The lookup singularity. Based on Spartan; built on Arkworks."
documentation = "https://github.com/a16z/lasso/README.md"
repository = "https://github.com/a16z/lasso"
license-file = "LICENSE"
keywords = ["zkSNARKs", "cryptography", "proofs"]

[dependencies]
ark-curve25519 = "0.4.0"
ark-ec = { version = "0.4.2", default-features = false }
ark-ff = { version = "0.4.2", default-features = false }
ark-serialize = { version = "0.4.2", default-features = false, features = [
    "derive",
] }
ark-std = { version = "0.4.0", default-features = false }
bellpepper-core = "0.2.1"
clap = { version = "4.3.10", features = ["derive"] }
colored = "2.0.0"
circom-scotia = "0.1.2"
criterion = { version = "0.5.1", features = ["html_reports"] }
dhat = "0.3.2"
digest = "0.8.1"
enum_dispatch = "0.3.12"
eyre = "0.6.9"
ff = "0.13.0"
hashbrown = "0.14.0"
itertools = "0.10.0"
merlin = "3.0.0"
num-integer = "0.1.45"
pasta_curves = "0.5.1"
plotters = "0.3.5"
rand = "0.7.3"
rand_chacha = { version = "0.3.0", default-features = false }
rand_core = { version = "0.5", default-features = false }
rayon = { version = "1.3.0", optional = true }
rgb = "0.8.37"
seq-macro = "0.3.3"
sha3 = "0.8.2"
strum = "0.25.0"
strum_macros = "0.25.2"
subtle = { version = "2.4", default-features = false }
textplots = "0.8.4"
thiserror = "1.0"
tracing = "0.1.37"
tracing-chrome = "0.7.1"
tracing-flame = "0.2.0"
tracing-subscriber = "0.3.17"
tracing-texray = "0.2.0"
zeroize = { version = "1", default-features = false }

common = { path = "../common" }
compiler = { path = "../compiler" }

witness = { git = "https://github.com/philsippl/circom-witness-rs", branch = "separate-witgen" }
ruint = "1.11.1"
spartan2 = { git = "https://github.com/a16z/Spartan2.git", branch = "non-relaxed-snark" }
# spartan2 = { path = "../Spartan2" }

[build-dependencies]
common = { path = "../common" }


[lib]
name = "liblasso"
path = "src/lib.rs"

[features]
default = [
    "ark-ec/parallel",
    "ark-ff/parallel",
    "ark-std/parallel",
    "ark-ff/asm",
    "multicore",
]
multicore = ["rayon"]
ark-msm = [] # run with arkworks MSM without small field element optimization
dhat-heap = []

[[bench]]
name = "sumcheck"
harness = false

[[bench]]
name = "dense_mlpoly"
harness = false

[[bench]]
name = "materialize"
harness = false
